### ISSUE TITLE
Malformed request

### ISSUE THREAD

**Issue by wmmihaa** [CenturyLinkCloud/Orchestrate-.NET-SDK#2]
Hi,
I'm running a Azure webjob picking messages of a queue and ran into an issue where it complains the request is malformed. I can run the same request in the portal without any problem.
```c#
public class Functions
{
    const string queueName = "tracking";
    static Application _application;
    static Client _client;
    static Collection _collection;
    // This function will get triggered/executed when a new message is written 
    // on an Azure Queue called queue.
    public static async Task ProcessQueueMessage([ServiceBusTrigger(queueName)] BrokeredMessage message, TextWriter logger)
    {
        try
        {
            if (_collection == null) {
                _application = new Application("...");

                // Create a Client
                _client = new Client(_application);

                // Get a Collection
                _collection = _client.GetCollection("tracking");
            }
            var bodyJson = new StreamReader(message.GetBody<Stream>(), Encoding.UTF8).ReadToEnd();
            var trackingMessage = JsonConvert.DeserializeObject(bodyJson);
            var key = Guid.NewGuid().ToString();
            await _collection.TryAddAsync("Key", key);
        }
        catch (Exception ex)
        {
            var m = ex.Message; // The API request is malformed.
        }
    }
}
```
I get an exception saying: “The API request is malformed.”, with no inner exception.

**Comment by jnewkirk** [comment]
After viewing the code did you intend the following code: 

`await _collection.TryAddAsync("Key", key);`

or did you intend the following: 

`await _collection.TryAddAsync(key, trackingMessage);` 

If you could let me know that will help me diagnose the issue. 

Thanks

**Comment by wmmihaa** [comment]
My bad, However I still get the same error:
trackingMessage = @"{""id"":42}";
var key = Guid.NewGuid().ToString();
await _collection.TryAddAsync(key, trackingMessage);

**Comment by wmmihaa** [comment]
Never mind, I thought I'd submit the json as text... Should have paid more attension ;)
